name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.SSH_USERNAME }}
          script: |
            cd ${{ secrets.APPLICATION_PATH }}
            git fetch
            git reset --hard origin/master
            ${{ secrets.COMPOSER_PATH }} install --no-interaction --prefer-dist --optimize-autoloader --classmap-authoritative --no-dev
            ${{ secrets.COMPOSER_PATH }} dump-autoload --optimize
